name: myapp

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  mysql:
    image: mysql
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_DATABASE: VMB_ENTERPRISE
      MYSQL_USER: vmbUser
      MYSQL_PASSWORD: vmbUser@123
      MYSQL_ROOT_PASSWORD: vmbUser@123
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    