spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vmb_enterprise?allowPublicKeyRetrieval=true&useSSL=false
    username: vmbUser
    password: vmbUser@123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bi_vs_consumer
    topic:
      message: sample-topic
    properties:
      security.protocol: PLAINTEXT
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#zookeeper start: bin/zookeeper-server-start.sh config/zookeeper.properties
#kafka start: bin/kafka-server-start.sh config/server.properties
#cmak start cd /home/kafka/Downloads/CMAK/target/universal/cmak-3.0.0.7/0